version: '3'
services:
  client:
    build: client
    depends_on:
      - datapower
    environment:
      - CONTINUOUS=true
  datapower:
    build: datapower
    stdin_open: true
    tty: true
    depends_on:
      - backend
    volumes:
      - ./datapower/config:/drouter/config
      - ./datapower/local:/drouter/local
      - ./datapower/cert:/secret:ro
    ports:
      - "9080:80"
      - "9443:443"
      - "9090:9090"
  backend:
    image: hstenzel/nodejs-hostname-automatic
