version: '3'
services:
  client:
    build: client
    depends_on:
      - datapower
  datapower:
    build: datapower
    stdin_open: true
    tty: true
    depends_on:
      - backend
    volumes:
      - ./datapower/cert:/secret:ro
  backend:
    image: hstenzel/nodejs-hostname-automatic
