version: '3.1'
services:
  client:
    build: client
    depends_on:
      - datapower
  datapower:
    build: datapower
    stdin_open: true
    tty: true
    depends_on:
      - backend
    secrets:
      - webgui_cert
      - webgui_key
      - server_cert
      - server_key
  backend:
    image: hstenzel/nodejs-hostname-automatic

secrets:
  webgui_cert:
    file: ./datapower/cert/webgui-sscert.pem
  webgui_key:
    file: ./datapower/cert/webgui-privkey.pem
  server_cert:
    file: ./datapower/cert/foo/server.crt
  server_key:
    file: ./datapower/cert/foo/server.key
